### ISSUE TITLE
Please fork https://github.com/icarito/image-builder-rpi.git

### ISSUE THREAD

**Issue by icarito** [publiclab/image-builder-rpi#4]
I've begun work on this, and have an image building process based on https://blog.hypriot.com/.
The contents of this repository have been put into a subdirectory of https://github.com/icarito/image-builder-rpi - please make me repo owner so I can place the jenkins hook. It'd be good if we could fork from the original? Not sure it can be done without loosing existing notes saved as issues in this repository.

Jenkins is building it btw :-)

**Comment by jywarren** [comment]
Hi, @icarito would you prefer we rename this repository `image-builder-rpi` and then you can merge in your work? That's probably the easiest way to preserve the issue history. 

Making you repo admin!

**Comment by icarito** [comment]
Thanks! Build process is setup now https://jenkins.laboratoriopublico.org/job/Raspberry%20Kit%20Image/

**Comment by icarito** [comment]
What is the way to link this repo with it's true parent fork at https://github.com/hypriot/image-builder-rpi ? Does it still involve email to github support? That would be ideal.

**Comment by jywarren** [comment]
I don't think we can at this point, since it wasn't originally forked from
there. But we can link back prominently!
